import {NAME} from "loteo/constants";

export const LOAD_WEEKLY_LOTTERY_INFO = `${NAME}/LOAD_WEEKLY_LOTTERY_INFO`;
export const SET_WEEKLY_LOTTERY_INFO = `${NAME}/SET_WEEKLY_LOTTERY_INFO`;

export const LOAD_APOLLO_DAILY_LOTTERY_INFO = `${NAME}/LOAD_APOLLO_DAILY_LOTTERY_INFO`;
export const SET_APOLLO_DAILY_LOTTERY_INFO = `${NAME}/SET_APOLLO_DAILY_LOTTERY_INFO`;

export const SET_CONVERSION_RATES = `${NAME}/SET_CONVERSION_RATES`;

export const LOAD_LAST_WINNERS = `${NAME}/LOAD_LAST_WINNERS`;
export const SET_LAST_WINNERS = `${NAME}/SET_LAST_WINNERS`;

export const LOAD_WEEKLY_LEADERBOARD = `${NAME}/LOAD_WEEKLY_LEADERBOARD`;
export const SET_WEEKLY_LEADERBOARD = `${NAME}/SET_WEEKLY_LEADERBOARD`;
export const ADD_WEEKLY_LEADERBOARD = `${NAME}/ADD_WEEKLY_LEADERBOARD`;

export const SET_TOTAL_STATS = `${NAME}/SET_TOTAL_STATS`;

export const LOAD_STATISTICS_USER = `${NAME}/LOAD_STATISTICS_USER`;
export const LOAD_STATISTICS_WEBVISITOR = `${NAME}/LOAD_STATISTICS_WEBVISITOR`;
export const LOAD_STATISTICS_PRODUCT = `${NAME}/LOAD_STATISTICS_PRODUCT`;
export const LOAD_STATISTICS_LOTTERY_TARGET = `${NAME}/LOAD_STATISTICS_LOTTERY_TARGET`;
export const LOAD_STATISTICS_AFFILIATE_SPACE = `${NAME}/LOAD_STATISTICS_AFFILIATE_SPACE`;
export const LOAD_STATISTICS_AFFILIATE_CHARITY = `${NAME}/LOAD_STATISTICS_AFFILIATE_CHARITY`;
export const LOAD_STATISTICS_LOTEU = `${NAME}/LOAD_STATISTICS_LOTEU`;
