Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.network :forwarded_port, guest: 4000, host: 4000
  config.vm.synced_folder "..", "/app"

  config.vm.provider "virtualbox" do |v|
    v.name = "loteo-dev"
  end

  config.vm.provision :shell, path: "scripts/post_install.sh", env: {"USE_NGINX" => ENV["USE_NGINX"]}
  config.vm.provision :shell, path: "scripts/setup.sh", privileged: false
  config.vm.provision :shell, path: "scripts/start.sh", privileged: false, run: "always", env: {"USE_NGINX" => ENV["USE_NGINX"]}
end
